// Mocks generated by Mockito 5.0.14 from annotations
// in easynvest_app/test/screens/cubit/investment_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:easynvest_app/data/dtos/investment_simulation_request.dart'
    as _i5;
import 'package:easynvest_app/data/investment_simulation_repository.dart'
    as _i3;
import 'package:easynvest_app/domain/investment_simulation_result.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeInvestmentSimulationResult_0 extends _i1.Fake
    implements _i2.InvestmentSimulationResult {}

/// A class which mocks [InvestmentSimulationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvestmentSimulationRepository extends _i1.Mock
    implements _i3.InvestmentSimulationRepository {
  MockInvestmentSimulationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.InvestmentSimulationResult> doSimulation(
          _i5.InvestmentSimulationRequest? request) =>
      (super.noSuchMethod(Invocation.method(#doSimulation, [request]),
              returnValue: Future<_i2.InvestmentSimulationResult>.value(
                  _FakeInvestmentSimulationResult_0()))
          as _i4.Future<_i2.InvestmentSimulationResult>);
  @override
  String toString() => super.toString();
}
